"use client";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/common/toast";
const schema = z.object({ title: z.string().min(5, "Nhập tên voucher tối thiểu 5 ký tự"), category: z.string().min(1, "Chọn danh mục"), originalPrice: z.coerce.number().positive("Giá gốc phải lớn hơn 0"), salePrice: z.coerce.number().min(0, "Giá bán không hợp lệ"), stock: z.coerce.number().int().positive("Số lượng phải lớn hơn 0"), expiry: z.string().min(1, "Chọn ngày hết hạn") }); type Values = z.infer<typeof schema>;
export function VoucherForm({ editing = false }: { editing?: boolean }) { const toast = useToast(); const router = useRouter(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: editing ? { title: "Giảm 30% tất cả combo bữa", category: "Ăn uống", originalPrice: 200000, salePrice: 140000, stock: 5000, expiry: "2026-09-30" } : { category: "Ăn uống", stock: 500 } }); return <form onSubmit={handleSubmit(async () => { await new Promise((resolve) => setTimeout(resolve, 350)); toast(editing ? "Đã lưu thay đổi voucher." : "Voucher đã gửi chờ duyệt."); router.push("/partner/vouchers"); })} className="rounded-xl border border-slate-200 bg-white p-6 shadow-brand-sm"><div className="grid gap-4 md:grid-cols-2"><Input label="Tên voucher" error={errors.title?.message} className="md:col-span-2" {...register("title")}/><label className="flex flex-col gap-1.5 text-xs font-semibold text-slate-700">Danh mục<select className="rounded-lg border-[1.5px] border-slate-200 px-3.5 py-2.5 text-sm font-normal outline-none focus:border-primary" {...register("category")}><option>Ăn uống</option><option>Mua sắm</option><option>Giải trí</option><option>Làm đẹp</option></select>{errors.category && <span className="text-danger">{errors.category.message}</span>}</label><Input label="Ngày hết hạn" type="date" error={errors.expiry?.message} {...register("expiry")}/><Input label="Giá gốc" type="number" error={errors.originalPrice?.message} {...register("originalPrice")}/><Input label="Giá bán" type="number" error={errors.salePrice?.message} {...register("salePrice")}/><Input label="Số lượng phát hành" type="number" error={errors.stock?.message} {...register("stock")}/><label className="flex flex-col gap-1.5 text-xs font-semibold text-slate-700">Ảnh voucher<input type="file" className="rounded-lg border border-dashed border-slate-300 p-2 text-xs" accept="image/*"/></label></div><label className="mt-5 flex flex-col gap-1.5 text-xs font-semibold text-slate-700">Mô tả & điều kiện<textarea className="min-h-28 rounded-lg border-[1.5px] border-slate-200 p-3 text-sm font-normal outline-none focus:border-primary" placeholder="Mô tả ưu đãi, điều kiện và chi nhánh áp dụng..."/></label><Button type="submit" className="mt-6" size="lg" disabled={isSubmitting}>{isSubmitting ? "Đang lưu..." : editing ? "Lưu thay đổi" : "Gửi duyệt voucher"}</Button></form>; }
