"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Logo } from "@/components/common/logo";
import { loginSchema, type LoginValues } from "@/lib/schemas/auth";
import { useSignIn } from "@/hooks/queries/use-auth";
import { dashboardForRole } from "@/features/auth/auth-api";
import { useToast } from "@/components/common/toast";
export default function LoginPage() { const router = useRouter(); const toast = useToast(); const signIn = useSignIn(); const { register, handleSubmit, formState: { errors } } = useForm<LoginValues>({ resolver: zodResolver(loginSchema), defaultValues: { remember: true } }); async function submit(values: LoginValues) { try { const data = await signIn.mutateAsync(values); toast("Chào mừng bạn quay trở lại ECVoucher!"); router.push(dashboardForRole(data.user.roleCode)); } catch (error) { toast(error instanceof Error ? error.message : "Không thể đăng nhập", "error"); } } return <main className="grid min-h-screen md:grid-cols-[1fr_480px]"><section className="relative hidden flex-col items-center justify-center overflow-hidden bg-gradient-to-br from-primary-dark via-primary to-indigo-500 p-16 text-center md:flex"><div className="absolute -left-24 -top-24 h-96 w-96 rounded-full bg-white/5"/><Logo light/><h1 className="mt-7 text-[28px] font-extrabold leading-tight tracking-[-.5px] text-white">Chào mừng<br/>trở lại!</h1><p className="mt-3 max-w-xs text-[15px] leading-7 text-white/70">Hàng nghìn deal đang chờ bạn. Đăng nhập để không bỏ lỡ bất kỳ ưu đãi nào.</p><div className="mt-10 flex gap-7 rounded-2xl bg-white/10 px-8 py-6 text-white"><Metric value="500K+" label="Voucher"/><Metric value="100%" label="Chính hãng"/><Metric value="5 phút" label="Giao ngay"/></div></section><section className="flex items-center justify-center bg-white p-6 sm:p-12"><form onSubmit={handleSubmit(submit)} className="w-full max-w-[384px]"><div className="mb-10 md:hidden"><Logo/></div><h2 className="text-2xl font-extrabold tracking-[-.5px] text-slate-900">Đăng nhập</h2><p className="mt-2 text-xs text-slate-500">Chưa có tài khoản? <Link className="font-semibold text-primary" href="/register">Đăng ký miễn phí →</Link></p><div className="mt-8 space-y-5"><Input label="Địa chỉ email" type="email" placeholder="ten@email.com" error={errors.email?.message} {...register("email")}/><Input label="Mật khẩu" type="password" placeholder="Nhập mật khẩu" error={errors.password?.message} hint={<Link href="/forgot-password">Quên mật khẩu?</Link>} {...register("password")}/><label className="flex items-center gap-2 text-xs text-slate-700"><input type="checkbox" className="h-4 w-4 accent-[#4F46E5]" {...register("remember")}/>Ghi nhớ đăng nhập 30 ngày</label><Button type="submit" size="lg" fullWidth disabled={signIn.isPending}>{signIn.isPending ? "Đang đăng nhập..." : "Đăng nhập"}</Button></div></form></section></main>; }
function Metric({ value, label }: { value: string; label: string }) { return <div><b className="block text-sm">{value}</b><span className="text-[11px] text-white/55">{label}</span></div>; }
